# Configuration for the Labeler action
# The action is set up in ./workflows/label.yml
# See https://github.com/actions/labeler for more details
ruby:
- "**/*.rb"

javascript:
- "**/*.js"

Tests! 🎉💖👏:
- "app/javascript/__tests__/**.test.js"
- "cypress/**/*.spec.js"
- "spec/**/*_spec.rb"

dependencies:
- "Gemfile*"
- "package*.json"
- "yarn.lock"
